import { readdir, readFile, writeFile } from "fs/promises";
import { join } from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface ComponentMeta {
  type: "react-native" | "react";
  name: string;
  description?: string;
  dependencies?: string[];
  variables?: Record<string, string | number>;
}

async function generateDocsRegistry() {
  const srcDir = join(__dirname, "..", "src");
  const outputPath = join(srcDir, "docs-registry.ts");

  console.log("🔍 Generating docs registry...");

  const entries = await readdir(srcDir, { withFileTypes: true });
  const components: ComponentMeta[] = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const metaPath = join(srcDir, entry.name, "meta.json");
      const readmePath = join(srcDir, entry.name, "README.mdx");

      try {
        const metaContent = await readFile(metaPath, "utf-8");
        const meta = JSON.parse(metaContent) as ComponentMeta;

        if (!meta.type || !meta.name) {
          continue;
        }

        try {
          await readFile(readmePath, "utf-8");
          components.push(meta);
          console.log(`✓ Found ${meta.name} with README.mdx`);
        } catch {
          continue;
        }
      } catch {
        continue;
      }
    }
  }

  components.sort((a, b) => a.name.localeCompare(b.name));

  const imports = components
    .map(
      (component) =>
        `import ${component.name.charAt(0).toUpperCase() + component.name.slice(1)}Docs from './${component.name}/README.mdx';`,
    )
    .join("\n");

  const registryEntries = components
    .map((component) => {
      const componentName =
        component.name.charAt(0).toUpperCase() + component.name.slice(1);
      return `  '${component.name}': ${componentName}Docs,`;
    })
    .join("\n");

  const content = `// This file is auto-generated by scripts/generate-docs-registry.ts
// Do not edit manually
import React from 'react';

${imports}

export const docsRegistry: Record<string, React.FC> = {
${registryEntries}
};
`;

  await writeFile(outputPath, content, "utf-8");

  console.log(`✅ Docs registry generated with ${components.length} components`);
  console.log(`📝 Written to: ${outputPath}`);
}

generateDocsRegistry().catch((error) => {
  console.error("❌ Failed to generate docs registry:", error);
  process.exit(1);
});
