// This file is auto-generated by scripts/generate-docs-registry.ts
// Do not edit manually
import React from 'react';

import TypographyDocs from './typography/README.mdx';

export const docsRegistry: Record<string, React.FC> = {
  'typography': TypographyDocs,
};
